apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-e2e-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-e2e-component
    app.kubernetes.io/part-of: fbc-e2e-application
  name: fbc-e2e-component
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: fbc-e2e-component
status:
  loadBalancer: {}
